"""NOXUND deterministic Data/AI pipeline.

Entity Resolution is the only generative boundary. Its core is implemented as
regex-first code with deterministic validation, durable replay ports, and a
default-deny review queue. No report number is generated by AI.
"""

from .entity_resolution import (
    PROMPT_VERSION,
    RESOLVER_VERSION,
    EntityResolver,
    RawVideo,
    ResolutionDecision,
    ResolutionMethod,
    candidate_is_supported,
    normalize_for_match,
)

__all__ = [
    "PROMPT_VERSION",
    "RESOLVER_VERSION",
    "EntityResolver",
    "RawVideo",
    "ResolutionDecision",
    "ResolutionMethod",
    "candidate_is_supported",
    "normalize_for_match",
]

__version__ = "0.1.0"
